parameters:
#    training_product.example.class: Training\ProductBundle\Example

services:
#    training_product.example:
#        class: %training_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
