Training\ProductBundle\Entity\Product:
    type: entity
    table: training_product
    repositoryClass: Training\ProductBundle\Entity\ProductRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        price:
            type: decimal
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    manyToMany:
        categories:
          targetEntity: Training\ProductBundle\Entity\Category
          inversedBy: products
          joinTable:
            name: training_product_category
            joinColumns:
              product_id:
                referencedColumnName: id
            inverseJoinColumns:
              category_id:
                referencedColumnName: id
    lifecycleCallbacks: {  }
