parameters:
#    training_blog.example.class: Training\BlogBundle\Example

services:
#    training_blog.example:
#        class: %training_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
