Training\BlogBundle\Entity\Category:
    type: entity
    table: training_blog_category
    repositoryClass: Training\BlogBundle\Entity\CategoryRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
    manyToOne:
        posts:
          targetEntity: Category
          joinColumn:
            name: category_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
