Training\BlogBundle\Entity\Post:
    type: entity
    table: training_blog_post
    repositoryClass: Training\BlogBundle\Entity\PostRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: 255
            unique: true
        excerpt:
            type: text
            nullable: true
        body:
            type: text
        author:
            type: string
            length: 255
        enabled:
            type: boolean
        isActive:
            type: boolean
            column: is_active
    manyToOne:
        category:
          targetEntity: Category
          joinColumn:
            name: category_id
            referencedColumnName: id
    manyToMany:
        tags:
          targetEntity: Tag
          inversedBy: posts
          joinTable:
            name: training_blog_post_tags
            joinColumns:
              post_id:
                referencedColumnName: id
            inverseJoinColumns:
              tag_id:
                referencedColumnName: id
    lifecycleCallbacks: {  }
